export const cityList = [
  { name: "Abuja", timezone: "Africa/Lagos" },
  { name: "Adelaide", timezone: "Australia/Adelaide" },
  { name: "Algiers", timezone: "Africa/Algiers" },
  { name: "Auckland", timezone: "Pacific/Auckland" },
  { name: "Ankara", timezone: "Europe/Istanbul" },
  { name: "Antwerp", timezone: "Europe/Brussels" },
  { name: "Asunción", timezone: "America/Asuncion" },
  { name: "Athens", timezone: "Europe/Athens" },
  { name: "Amsterdam", timezone: "Europe/Amsterdam" },
  { name: "Bangkok", timezone: "Asia/Bangkok" },
  { name: "Barcelona", timezone: "Europe/Madrid" },
  { name: "Beijing", timezone: "Asia/Shanghai" },
  { name: "Berlin", timezone: "Europe/Berlin" },
  { name: "Buenos Aires", timezone: "America/Argentina/Buenos_Aires" },
  { name: "Baghdad", timezone: "Asia/Baghdad" },
  { name: "Baku", timezone: "Asia/Baku" },
  { name: "Baltimore", timezone: "America/New_York" },
  { name: "Bangui", timezone: "Africa/Bangui" },
  { name: "Banjul", timezone: "Africa/Banjul" },
  { name: "Beirut", timezone: "Asia/Beirut" },
  { name: "Belo Horizonte", timezone: "America/Sao_Paulo" },
  { name: "Bordeaux", timezone: "Europe/Paris" },
  { name: "Brisbane", timezone: "Australia/Brisbane" },
  { name: "Bristol", timezone: "Europe/London" },
  { name: "Bucharest", timezone: "Europe/Bucharest" },
  { name: "Budapest", timezone: "Europe/Budapest" },
  { name: "Cairo", timezone: "Africa/Cairo" },
  { name: "Chicago", timezone: "America/Chicago" },
  { name: "Copenhagen", timezone: "Europe/Copenhagen" },
  { name: "Catania", timezone: "Europe/Rome" },
  { name: "Chennai", timezone: "Asia/Kolkata" },
  { name: "Chattanooga", timezone: "America/New_York" },
  { name: "Cleveland", timezone: "America/New_York" },
  { name: "Colombo", timezone: "Asia/Colombo" },
  { name: "Delhi", timezone: "Asia/Kolkata" },
  { name: "Dhaka", timezone: "Asia/Dhaka" },
  { name: "Dubai", timezone: "Asia/Dubai" },
  { name: "Durban", timezone: "Africa/Johannesburg" },
  { name: "Dublin", timezone: "Europe/Dublin" },
  { name: "Edinburgh", timezone: "Europe/London" },
  { name: "Frankfurt", timezone: "Europe/Berlin" },
  { name: "Freetown", timezone: "Africa/Freetown" },
  { name: "Hawaii", timezone: "Pacific/Honolulu" },
  { name: "Helsinki", timezone: "Europe/Helsinki" },
  { name: "Hong Kong", timezone: "Asia/Hong_Kong" },
  { name: "Ho Chi Minh City", timezone: "Asia/Ho_Chi_Minh" },
  { name: "Hanoi", timezone: "Asia/Ho_Chi_Minh" },
  { name: "Hobart", timezone: "Australia/Hobart" },
  { name: "Geneva", timezone: "Europe/Zurich" },
  { name: "Genoa", timezone: "Europe/Rome" },
  { name: "Grahamstown", timezone: "Africa/Johannesburg" },
  { name: "Guadalajara", timezone: "America/Mexico_City" },
  { name: "Istanbul", timezone: "Europe/Istanbul" },
  { name: "Ibadan", timezone: "Africa/Lagos" },
  { name: "Iquitos", timezone: "America/Lima" },
  { name: "Jakarta", timezone: "Asia/Jakarta" },
  { name: "Jeddah", timezone: "Asia/Riyadh" },
  { name: "Jerusalem", timezone: "Asia/Jerusalem" },
  { name: "Johannesburg", timezone: "Africa/Johannesburg" },
  { name: "Kabul", timezone: "Asia/Kabul" },
  { name: "Kampala", timezone: "Africa/Kampala" },
  { name: "Kigali", timezone: "Africa/Kigali" },
  { name: "Kolkata", timezone: "Asia/Kolkata" },
  { name: "Kuala Lumpur", timezone: "Asia/Kuala_Lumpur" },
  { name: "Lagos", timezone: "Africa/Lagos" },
  { name: "Lima", timezone: "America/Lima" },
  { name: "Lisbon", timezone: "Europe/Lisbon" },
  { name: "London", timezone: "Europe/London" },
  { name: "Los Angeles", timezone: "America/Los_Angeles" },
  { name: "Lyon", timezone: "Europe/Paris" },
  { name: "Madrid", timezone: "Europe/Madrid" },
  { name: "Manila", timezone: "Asia/Manila" },
  { name: "Melbourne", timezone: "Australia/Melbourne" },
  { name: "Mexico City", timezone: "America/Mexico_City" },
  { name: "Malabo", timezone: "Africa/Malabo" },
  { name: "Malmö", timezone: "Europe/Stockholm" },
  { name: "Monaco", timezone: "Europe/Monaco" },
  { name: "Montpellier", timezone: "Europe/Paris" },
  { name: "Miami", timezone: "America/New_York" },
  { name: "Milan", timezone: "Europe/Rome" },
  { name: "Montreal", timezone: "America/Toronto" },
  { name: "Moscow", timezone: "Europe/Moscow" },
  { name: "Mumbai", timezone: "Asia/Kolkata" },
  { name: "Munich", timezone: "Europe/Berlin" },
  { name: "Nairobi", timezone: "Africa/Nairobi" },
  { name: "Nassau", timezone: "America/Nassau" },
  { name: "Nice", timezone: "Europe/Paris" },
  { name: "New Delhi", timezone: "Asia/Kolkata" },
  { name: "New York", timezone: "America/New_York" },
  { name: "Osaka", timezone: "Asia/Tokyo" },
  { name: "Oslo", timezone: "Europe/Oslo" },
  { name: "Paris", timezone: "Europe/Paris" },
  { name: "Prague", timezone: "Europe/Prague" },
  { name: "Porto", timezone: "Europe/Lisbon" },
  { name: "Quito", timezone: "America/Lima" },
  { name: "Rio de Janeiro", timezone: "America/Sao_Paulo" },
  { name: "Riga", timezone: "Europe/Riga" },
  { name: "Riyadh", timezone: "Asia/Riyadh" },
  { name: "Rome", timezone: "Europe/Rome" },
  { name: "San Francisco", timezone: "America/Los_Angeles" },
  { name: "Santiago", timezone: "America/Santiago" },
  { name: "São Paulo", timezone: "America/Sao_Paulo" },
  { name: "Salvador", timezone: "America/Bahia" },
  { name: "Shanghai", timezone: "Asia/Shanghai" },
  { name: "Sofia", timezone: "Europe/Sofia" },
  { name: "Stockholm", timezone: "Europe/Stockholm" },
  { name: "Seoul", timezone: "Asia/Seoul" },
  { name: "Singapore", timezone: "Asia/Singapore" },
  { name: "Sydney", timezone: "Australia/Sydney" },
  { name: "Tallinn", timezone: "Europe/Tallinn" },
  { name: "Tunis", timezone: "Africa/Tunis" },
  { name: "Taipei", timezone: "Asia/Taipei" },
  { name: "Tel Aviv", timezone: "Asia/Jerusalem" },
  { name: "Tokyo", timezone: "Asia/Tokyo" },
  { name: "Toronto", timezone: "America/Toronto" },
  { name: "Tashkent", timezone: "Asia/Tashkent" },
  { name: "Ulaanbaatar", timezone: "Asia/Ulaanbaatar" },
  { name: "Vancouver", timezone: "America/Vancouver" },
  { name: "Valencia", timezone: "Europe/Madrid" },
  { name: "Vilnius", timezone: "Europe/Vilnius" },
  { name: "Vienna", timezone: "Europe/Vienna" },
  { name: "Warsaw", timezone: "Europe/Warsaw" },
  { name: "Washington DC", timezone: "America/New_York" },
  { name: "Wellington", timezone: "Pacific/Auckland" },
  { name: "Zagreb", timezone: "Europe/Zagreb" },
  { name: "Zurich", timezone: "Europe/Zurich" }
];